export default [
  {
    id: "d1",
    titulo: "Ultrabook 14\"",
    imagen: "/imagenes/destacado1.jpg",
    categoria: "Computo",
    precio: 3699,
    stock: 8,
    descripcion: "Equipo liviano para trabajo, estudio y productividad diaria.",
    rating: 4.7,
    reseñas: 128,
    badge: "Oferta",
  },
  {
    id: "d2",
    titulo: "Monitor 27\" 4K",
    imagen: "/imagenes/destacado2.jpg",
    categoria: "Monitores",
    precio: 1599,
    stock: 12,
    descripcion: "Panel de alta nitidez para oficina, diseño y entretenimiento.",
    rating: 4.6,
    reseñas: 94,
    badge: "Recomendado",
  },
  {
    id: "d3",
    titulo: "Auriculares inalámbricos",
    imagen: "/imagenes/destacado3.jpg",
    categoria: "Audio",
    precio: 399,
    stock: 20,
    descripcion: "Sonido claro y buena autonomía para uso en casa u oficina.",
    rating: 4.5,
    reseñas: 210,
    badge: "Nuevo",
  },
];
