export default [
  {
    id: "c1",
    titulo: "Teclado mecánico",
    imagen: "/imagenes/catalogo1.jpg",
    categoria: "Perifericos",
    precio: 299,
    stock: 16,
    rating: 4.4,
    reseñas: 330,
    badge: "Hot",
  },
  {
    id: "c2",
    titulo: "Mouse gaming",
    imagen: "/imagenes/catalogo2.jpg",
    categoria: "Perifericos",
    precio: 179,
    stock: 24,
    rating: 4.3,
    reseñas: 290,
    badge: "Oferta",
  },
  {
    id: "c3",
    titulo: "Disco SSD 1 TB",
    imagen: "/imagenes/catalogo3.jpg",
    categoria: "Almacenamiento",
    precio: 449,
    stock: 10,
    rating: 4.8,
    reseñas: 410,
    badge: "Top",
  },
  {
    id: "c4",
    titulo: "Webcam HD",
    imagen: "/imagenes/catalogo4.jpg",
    categoria: "Streaming",
    precio: 189,
    stock: 14,
    rating: 4.2,
    reseñas: 152,
    badge: "Nuevo",
  },
];
